export const comfyUiResearchPlan = {
  goalTitle: '30 天学会 ComfyUI',
  days: 30,
  dailyMinutes: 30,
  level: '零基础',
  researchSummary: {
    topic: 'ComfyUI',
    sourceNames: 'ComfyUI Documentation、ComfyUI GitHub',
    method: [
      '每天先复现一个最小工作流，再改一个参数观察变化',
      '建立自己的 workflow 文件夹，保存每次可复现的 JSON',
      '遇到节点报错时先记录缺失模型、缺失自定义节点、路径错误三类原因',
    ],
    note: '已根据 ComfyUI 官方文档和 GitHub 资料生成 30 天学习路线。',
  },
  boss: {
    name: 'ComfyUI节点工作流焦虑',
    tag: '第 1 天 Boss',
    hp: 68,
    task: '阅读安装要求并确认 Python/GPU/模型目录',
    micro: '打开 ComfyUI 文档，确认安装方式和模型目录',
    time: '14 分钟',
    mood: 'calm',
    quote: '先跑通一个最小闭环，再慢慢加复杂度。',
  },
  mapNodes: [
    { title: '1. 安装与模型准备', detail: '1/8 今日推进', active: true, done: false },
    { title: '2. 理解节点和工作流', detail: '预计 8 个小任务', active: false, done: false },
    { title: '3. 文生图与图生图实战', detail: '预计 8 个小任务', active: false, done: false },
    { title: '4. 进阶工作流与自定义节点', detail: '预计 8 个小任务', active: false, done: false },
  ],
  dailyTasks: [
    { title: '阅读安装要求并确认 Python/GPU/模型目录', day: 1, minutes: 14, method: '每天先复现一个最小工作流，再改一个参数观察变化' },
    { title: '完成 ComfyUI 启动，并保存第一张测试图', day: 2, minutes: 19, method: '建立自己的 workflow 文件夹，保存每次可复现的 JSON' },
    { title: '拆解一个基础文生图 workflow 的核心节点', day: 3, minutes: 24, method: '遇到节点报错时先记录缺失模型、缺失自定义节点、路径错误三类原因' },
    { title: '修改 prompt、采样器和步数，记录输出差异', day: 4, minutes: 14, method: '每天先复现一个最小工作流，再改一个参数观察变化' },
  ],
  fullPlan: [
    { day: 1, chapter: '安装与模型准备', title: '阅读安装要求并确认 Python/GPU/模型目录', minutes: 14, method: '每天先复现一个最小工作流，再改一个参数观察变化', output: '留下一个可复现记录' },
    { day: 2, chapter: '安装与模型准备', title: '完成 ComfyUI 启动，并保存第一张测试图', minutes: 19, method: '建立自己的 workflow 文件夹，保存每次可复现的 JSON', output: '留下一个可复现记录' },
    { day: 3, chapter: '安装与模型准备', title: '拆解一个基础文生图 workflow 的核心节点', minutes: 24, method: '遇到节点报错时先记录缺失模型、缺失自定义节点、路径错误三类原因', output: '留下一个可复现记录' },
    { day: 4, chapter: '安装与模型准备', title: '修改 prompt、采样器和步数，记录输出差异', minutes: 14, method: '每天先复现一个最小工作流，再改一个参数观察变化', output: '留下一个可复现记录' },
    { day: 5, chapter: '安装与模型准备', title: '完成图生图或局部重绘的最小工作流', minutes: 19, method: '建立自己的 workflow 文件夹，保存每次可复现的 JSON', output: '留下一个可复现记录' },
    { day: 6, chapter: '安装与模型准备', title: '安装 ComfyUI-Manager 并修复一个缺失节点', minutes: 24, method: '遇到节点报错时先记录缺失模型、缺失自定义节点、路径错误三类原因', output: '留下一个可复现记录' },
    { day: 7, chapter: '安装与模型准备', title: '复用一个社区 workflow，写下每个节点作用', minutes: 14, method: '每天先复现一个最小工作流，再改一个参数观察变化', output: '留下一个可复现记录' },
    { day: 8, chapter: '安装与模型准备', title: '整理本阶段问题清单并修正模型路径', minutes: 19, method: '建立自己的 workflow 文件夹，保存每次可复现的 JSON', output: '跑通本地 ComfyUI，并加载一个基础模型' },
    { day: 9, chapter: '理解节点和工作流', title: '画出 checkpoint、CLIP、VAE、sampler 的连接关系', minutes: 24, method: '遇到节点报错时先记录缺失模型、缺失自定义节点、路径错误三类原因', output: '留下一个可复现记录' },
    { day: 10, chapter: '理解节点和工作流', title: '拆解 prompt 正向和反向提示词的作用', minutes: 14, method: '每天先复现一个最小工作流，再改一个参数观察变化', output: '留下一个可复现记录' },
  ],
  next: '安装与模型目录检查',
  sources: [
    { title: 'ComfyUI Documentation', url: 'https://docs.comfy.org/', status: 'live' },
    { title: 'ComfyUI GitHub', url: 'https://github.com/comfyanonymous/ComfyUI', status: 'live' },
  ],
}
